
# Look for the header file.
FIND_PATH(LIBB64_INCLUDE_DIR NAMES b64/encode.h)

# Look for the library.
FIND_LIBRARY(LIBB64_LIBRARY NAMES b64)

# Handle the QUIETLY and REQUIRED arguments and set LIBB64_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBB64 DEFAULT_MSG LIBB64_LIBRARY LIBB64_INCLUDE_DIR)

# Copy the results to the output variables.
IF(LIBB64_FOUND)
	SET(LIBB64_LIBRARIES ${LIBB64_LIBRARY})
	SET(LIBB64_INCLUDE_DIRS ${LIBB64_INCLUDE_DIR})
ELSE(LIBB64_FOUND)
	SET(LIBB64_LIBRARIES)
	SET(LIBB64_INCLUDE_DIRS)
ENDIF(LIBB64_FOUND)

MARK_AS_ADVANCED(LIBB64_INCLUDE_DIRS LIBB64_LIBRARIES)

