
# Look for the header file.
FIND_PATH(CPPUNIT_INCLUDE_DIR NAMES cppunit/TestSuite.h)

# Look for the library.
FIND_LIBRARY(CPPUNIT_LIBRARY NAMES cppunit)

# Handle the QUIETLY and REQUIRED arguments and set CPPUNIT_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPPUNIT DEFAULT_MSG CPPUNIT_LIBRARY CPPUNIT_INCLUDE_DIR)

# Copy the results to the output variables.
IF(CPPUNIT_FOUND)
	SET(CPPUNIT_LIBRARIES ${CPPUNIT_LIBRARY})
	SET(CPPUNIT_INCLUDE_DIRS ${CPPUNIT_INCLUDE_DIR})
ELSE(CPPUNIT_FOUND)
	SET(CPPUNIT_LIBRARIES)
	SET(CPPUNIT_INCLUDE_DIRS)
ENDIF(CPPUNIT_FOUND)

MARK_AS_ADVANCED(CPPUNIT_INCLUDE_DIRS CPPUNIT_LIBRARIES)

