
# Look for the header file.
FIND_PATH(PCRECPP_INCLUDE_DIR NAMES pcrecpp.h)

# Look for the library.
FIND_LIBRARY(PCRECPP_LIBRARY NAMES pcrecpp)

# Handle the QUIETLY and REQUIRED arguments and set PCRECPP_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRECPP DEFAULT_MSG PCRECPP_LIBRARY PCRECPP_INCLUDE_DIR)

# Copy the results to the output variables.
IF(PCRECPP_FOUND)
	SET(PCRECPP_LIBRARIES ${PCRECPP_LIBRARY})
	SET(PCRECPP_INCLUDE_DIRS ${PCRECPP_INCLUDE_DIR})
ELSE(PCRECPP_FOUND)
	SET(PCRECPP_LIBRARIES)
	SET(PCRECPP_INCLUDE_DIRS)
ENDIF(PCRECPP_FOUND)

MARK_AS_ADVANCED(PCRECPP_INCLUDE_DIRS PCRECPP_LIBRARIES)

